language: ruby
rvm:
  - 2.7.1
env:
  matrix:
    - TEST_SUITE=default
    - TEST_SUITE=proof
matrix:
  allow_failures:
    - env: TEST_SUITE=proof
  include:
    - stage: deploy
      env:
        - TEST_SUITE=deploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: _site
        target_branch: master
        on:
          branch: source
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - openjdk-8-jre
cache:
  bundler: true
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
before_install:
  - gem update --system
  - gem install bundler
  - nvm install node
install:
  - bundle install --jobs=3 --retry=3
  - pip install --user html5validator
  - npm install -g pa11y-ci
script:
  - script/travis-ci
branches:
  only:
    - source
