language: ruby
cache: bundler
rvm:
  - 2.6.4
env:
  matrix:
    - TEST_SUITE=default
    - TEST_SUITE=proof
matrix:
  allow_failures:
    - env: TEST_SUITE=proof
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - openjdk-8-jre
cache:
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
before_install:
  - gem update --system
  - gem install bundler
  - nvm install node
install:
  - bundle install --jobs=3 --retry=3
  - pip install --user html5validator
  - npm install -g pa11y-ci
script:
  - script/travis-ci
branches:
  only:
    - source
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _site
  target-branch: master
  on:
    branch: source
