language: ruby
cache: bundler
rvm:
  - 2.6.3
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - openjdk-8-jre
cache:
  directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
before_install:
  - gem update --system
  - gem install bundler
install:
  - pip install --user html5validator
script:
  - bundle exec rake spec
  - bundle exec jekyll clean
  - bundle exec jekyll build
  - html5validator -Werror --also-check-css --also-check-svg --root _site/
  - bundle exec rake proof
branches:
  only:
    - source
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: _site
  target-branch: master
  on:
    branch: source
