# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yous
author: Yous
email:
description: Blog for hackers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yous.be" # the base hostname & protocol for your site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - spec
  - vendor
timezone: UTC

# Social media
twitter_username:
twitter_image: http://yous.be/images/about/yous.png
github_username: yous
facebook_app_id: 100001802412550
facebook_image: http://yous.be/images/about/yous.png
google_analytics_id: UA-43111808-1

# Plugins
gems:
  - jekyll-archives
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: kramdown
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - footnotes
    - smart

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/

# jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
