# Site settings
title: Yous
author: Yous
email:
description: Blog for hackers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yous.be" # the base hostname & protocol for your site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - spec
  - vendor

# Social media
twitter_username:
twitter_image: http://yous.be/images/about/yous.png
github_username: yous
facebook_app_id: 100001802412550
facebook_image: http://yous.be/images/about/yous.png
google_analytics_id: UA-43111808-1

# Plugins
gems:
  - jekyll-archives
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: redcarpet
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - footnotes
    - smart

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/

# jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
