# Site settings
title: Yous
email:
description: > # this means to ignore newlines until "baseurl:"
  for hackers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yous.be" # the base hostname & protocol for your site
twitter_username:
github_username: yous

# Plugins
gems:
  - jekyll-redirect-from

# Build settings
markdown: redcarpet
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - footnotes
    - smart
