# Site settings
title: Yous
author: Yous
email:
description: Blog for hackers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yous.be" # the base hostname & protocol for your site
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Social media
twitter_username:
twitter_image: http://yous.be/images/about/Super-Hexagon.png
github_username: yous
facebook_app_id: 100001802412550
facebook_image: http://yous.be/images/about/Super-Hexagon.png

# Plugins
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: redcarpet
excerpt_separator: "<!-- more -->"

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

# Markdown settings
redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - footnotes
    - smart
