# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yous
author: Yous
description: Blog for hackers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yous.be" # the base hostname & protocol for your site, e.g. http://example.com
theme: jekyll-whiteglass
timezone: UTC
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - cscope.out
  - spec
  - tags
  - tmp
  - vendor

# Social media
twitter_username:
twitter_image: http://yous.be/images/about/yous.png
github_username: yous
facebook_app_id: 100001802412550
facebook_image: http://yous.be/images/about/yous.png
google_analytics: UA-43111808-1

# Plugins
plugins:
  - jekyll-archives
  - jekyll-gist
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sourcemap: never

# Outputting
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5
feed:
  path: atom.xml

# Markdown settings
# See https://kramdown.gettalong.org/options.html.
kramdown:
  auto_id_stripping: true
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  gfm_quirks: [paragraph_end]
  hard_wrap: false
  input: GFM
  smart_quotes: [lsquo, rsquo, ldquo, rdquo]
  toc_levels: 1..6

redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink
    - strikethrough
    - superscript
    - footnotes
    - smart

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/

# jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
