version: 2.1

orbs:
  ruby: circleci/ruby@1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0-node
        environment:
          NPM_CONFIG_PREFIX: '~/.npm-global'
    steps:
      - checkout
      - ruby/install-deps
      - run: echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - npm-{{ arch }}
      - run: npm install -g pa11y-ci
      - save_cache:
          key: npm-{{ arch }}
          paths:
            - ~/.npm
            - ~/.npm-global
      - run: |
          bundle exec jekyll clean
          bundle exec jekyll build
          bundle exec rake spec
      - run: script/pa11y-ci
      - persist_to_workspace:
          root: .
          paths:
            - _site
  validate:
    docker:
      - image: cimg/python:3.9-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - pypi-{{ checksum "/home/circleci/.pyenv/version" }}
      - run: pip install -U html5validator
      - save_cache:
          key: pypi-{{ checksum "/home/circleci/.pyenv/version" }}
          paths:
            - /home/circleci/.cache/pip
            - /home/circleci/.pyenv/versions/
            - /home/circleci/.local/lib/
      - attach_workspace:
          at: .
      - run: html5validator --Werror --also-check-css --also-check-svg --root _site/
  proof:
    docker:
      - image: cimg/ruby:3.0
    steps:
      - checkout
      - ruby/install-deps
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - htmlproofer-{{ arch }}
      - run: bundle exec rake proof || true
      - save_cache:
          key: htmlproofer-{{ arch }}
          paths:
            - tmp/.htmlproofer
  deploy:
    docker:
      - image: cimg/node:16.5
        environment:
          NPM_CONFIG_PREFIX: '~/.npm-global'
    steps:
      - checkout
      - run: echo 'export PATH=~/.npm-global/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - npm-{{ arch }}
      - run: npm install -g gh-pages
      - save_cache:
          key: npm-{{ arch }}
          paths:
            - ~/.npm
            - ~/.npm-global
      - attach_workspace:
          at: .
      - run: |
          git config user.name "$(git --no-pager show --no-patch --format='%an')"
          git config user.email "$(git --no-pager show --no-patch --format='%ae')"
      - run:
          command: gh-pages --branch master --dist _site
          environment:
            CACHE_DIR: "~/.npm-global/.cache"
            GITHUB_TOKEN: "$GITHUB_TOKEN"

workflows:
  version: 2
  build:
    jobs:
      - build
      - validate:
          requires:
            - build
      - proof:
          requires:
            - build
      - deploy:
          context: yous.be
          requires:
            - build
            - validate
          filters:
            branches:
              only: source
